// Code generated by MockGen. DO NOT EDIT.
// Source: connection.go
//
// Generated by this command:
//
//	mockgen -source=connection.go -package=mocks -destination=../mocks/poi_mock.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	gomock "go.uber.org/mock/gomock"
)

// MockConnection is a mock of Connection interface.
type MockConnection struct {
	ctrl     *gomock.Controller
	recorder *MockConnectionMockRecorder
	isgomock struct{}
}

// MockConnectionMockRecorder is the mock recorder for MockConnection.
type MockConnectionMockRecorder struct {
	mock *MockConnection
}

// NewMockConnection creates a new mock instance.
func NewMockConnection(ctrl *gomock.Controller) *MockConnection {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnection) EXPECT() *MockConnectionMockRecorder {
	_ = "STUB: not implemented"

	// AddConfig mocks base method.
	return nil
}

func (m *MockConnection) AddConfig(ctx context.Context, key, value string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// AddConfig indicates an expected call of AddConfig.
func (mr *MockConnectionMockRecorder) AddConfig(ctx, key, value any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CheckoutBranch mocks base method.
func (m *MockConnection) CheckoutBranch(ctx context.Context, branchName string, detach bool) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// CheckoutBranch indicates an expected call of CheckoutBranch.
func (mr *MockConnectionMockRecorder) CheckoutBranch(ctx, branchName, detach any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteBranches mocks base method.
func (m *MockConnection) DeleteBranches(ctx context.Context, branchNames []string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// DeleteBranches indicates an expected call of DeleteBranches.
func (mr *MockConnectionMockRecorder) DeleteBranches(ctx, branchNames any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetAssociatedRefNames mocks base method.
func (m *MockConnection) GetAssociatedRefNames(ctx context.Context, oid string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// GetAssociatedRefNames indicates an expected call of GetAssociatedRefNames.
func (mr *MockConnectionMockRecorder) GetAssociatedRefNames(ctx, oid any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetBranchNames mocks base method.
func (m *MockConnection) GetBranchNames(ctx context.Context) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// GetBranchNames indicates an expected call of GetBranchNames.
func (mr *MockConnectionMockRecorder) GetBranchNames(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetConfig mocks base method.
func (m *MockConnection) GetConfig(ctx context.Context, key string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockConnectionMockRecorder) GetConfig(ctx, key any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetLog mocks base method.
func (m *MockConnection) GetLog(ctx context.Context, branchName string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// GetLog indicates an expected call of GetLog.
func (mr *MockConnectionMockRecorder) GetLog(ctx, branchName any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetMergedBranchNames mocks base method.
func (m *MockConnection) GetMergedBranchNames(ctx context.Context, remoteName, branchName string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// GetMergedBranchNames indicates an expected call of GetMergedBranchNames.
func (mr *MockConnectionMockRecorder) GetMergedBranchNames(ctx, remoteName, branchName any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetPullRequests mocks base method.
func (m *MockConnection) GetPullRequests(ctx context.Context, hostname, orgs, repos, queryHashes string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// GetPullRequests indicates an expected call of GetPullRequests.
func (mr *MockConnectionMockRecorder) GetPullRequests(ctx, hostname, orgs, repos, queryHashes any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetRemoteNames mocks base method.
func (m *MockConnection) GetRemoteNames(ctx context.Context) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// GetRemoteNames indicates an expected call of GetRemoteNames.
func (mr *MockConnectionMockRecorder) GetRemoteNames(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetRepoNames mocks base method.
func (m *MockConnection) GetRepoNames(ctx context.Context, hostname, repoName string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// GetRepoNames indicates an expected call of GetRepoNames.
func (mr *MockConnectionMockRecorder) GetRepoNames(ctx, hostname, repoName any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetSshConfig mocks base method.
func (m *MockConnection) GetSshConfig(ctx context.Context, name string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// GetSshConfig indicates an expected call of GetSshConfig.
func (mr *MockConnectionMockRecorder) GetSshConfig(ctx, name any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetUncommittedChanges mocks base method.
func (m *MockConnection) GetUncommittedChanges(ctx context.Context, opts ...string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// GetUncommittedChanges indicates an expected call of GetUncommittedChanges.
func (mr *MockConnectionMockRecorder) GetUncommittedChanges(ctx any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetWorktrees mocks base method.
func (m *MockConnection) GetWorktrees(ctx context.Context) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// GetWorktrees indicates an expected call of GetWorktrees.
func (mr *MockConnectionMockRecorder) GetWorktrees(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RemoveConfig mocks base method.
func (m *MockConnection) RemoveConfig(ctx context.Context, key string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// RemoveConfig indicates an expected call of RemoveConfig.
func (mr *MockConnectionMockRecorder) RemoveConfig(ctx, key any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RemoveWorktree mocks base method.
func (m *MockConnection) RemoveWorktree(ctx context.Context, path string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// RemoveWorktree indicates an expected call of RemoveWorktree.
func (mr *MockConnectionMockRecorder) RemoveWorktree(ctx, path any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
